import type { EventDefinition } from './types.js';
import {
  EventDomain, EventFrequency, EventImportance, EventMultiplier,
  EventSector, EventTimeMode, EventType, EventUnit,
} from './types.js';

const US = {
  countryCode: 'US' as const,
  countryId: 840,
  currency: 'USD' as const,
  domain: EventDomain.Economic,
};

// ─── MONEY ───────────────────────────────────────────────────────────
const MONEY_EVENTS: readonly EventDefinition[] = [
  { id: 'US.MONEY.FED_RATE', name: 'Federal Reserve Interest Rate Decision', type: EventType.Indicator, sector: EventSector.Money, importance: EventImportance.High, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 2, externalIds: { slug: 'fed-rate' }, description: 'Federal Open Market Committee interest rate decision', ...US },
  { id: 'US.MONEY.FED_FUNDS_RATE', name: 'Fed Funds Rate', type: EventType.Indicator, sector: EventSector.Money, importance: EventImportance.High, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 2, description: 'Effective federal funds rate target', ...US },
  { id: 'US.MONEY.FOMC_MINUTES', name: 'FOMC Meeting Minutes', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.High, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Minutes from the Federal Open Market Committee meeting', ...US },
  { id: 'US.MONEY.FOMC_PRESS_CONF', name: 'FOMC Press Conference', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.High, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Federal Reserve Chair press conference after FOMC meeting', ...US },
  { id: 'US.MONEY.FED_CHAIR_SPEECH', name: 'Fed Chair Speech', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Speech by the Federal Reserve Chair', ...US },
  { id: 'US.MONEY.TREASURY_2YR', name: '2-Year Treasury Bond Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 2-year note auction yield', ...US },
  { id: 'US.MONEY.TREASURY_5YR', name: '5-Year Treasury Bond Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 5-year note auction yield', ...US },
  { id: 'US.MONEY.TREASURY_10YR', name: '10-Year Treasury Bond Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 10-year note auction yield', ...US },
  { id: 'US.MONEY.TREASURY_30YR', name: '30-Year Treasury Bond Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 30-year bond auction yield', ...US },
  { id: 'US.MONEY.M2_MONEY_SUPPLY', name: 'M2 Money Supply', type: EventType.Indicator, sector: EventSector.Money, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.USD, multiplier: EventMultiplier.Billions, digits: 1, description: 'M2 money supply aggregate', ...US },
  { id: 'US.MONEY.TREASURY_4WK', name: '4-Week Treasury Bill Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.None, frequency: EventFrequency.Week, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 4-week bill auction yield', ...US },
  { id: 'US.MONEY.TREASURY_3MO', name: '3-Month Treasury Bill Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.None, frequency: EventFrequency.Week, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 3-month bill auction yield', ...US },
  { id: 'US.MONEY.TREASURY_6MO', name: '6-Month Treasury Bill Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.None, frequency: EventFrequency.Week, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 6-month bill auction yield', ...US },
  { id: 'US.MONEY.TREASURY_1YR', name: '1-Year Treasury Bill Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 1-year bill auction yield', ...US },
  { id: 'US.MONEY.TREASURY_7YR', name: '7-Year Treasury Note Auction', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 3, description: 'US Treasury 7-year note auction yield', ...US },
  { id: 'US.MONEY.FED_MEETING_DAY2', name: 'FED Meeting (2nd Day)', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.High, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Second day of the FOMC two-day meeting (decision day)', ...US },
  { id: 'US.MONEY.HUMPHREY_HAWKINS', name: 'Humphrey Hawkins Testimony', type: EventType.Event, sector: EventSector.Money, importance: EventImportance.High, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Fed Chair semiannual monetary policy testimony to Congress', ...US },
] as const;

// ─── PRICES ──────────────────────────────────────────────────────────
const PRICES_EVENTS: readonly EventDefinition[] = [
  { id: 'US.PRICES.CPI_MOM', name: 'CPI M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, externalIds: { slug: 'us-cpi' }, description: 'Consumer Price Index month-over-month change', ...US },
  { id: 'US.PRICES.CPI_YOY', name: 'CPI Y/Y', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Consumer Price Index year-over-year change', ...US },
  { id: 'US.PRICES.CORE_CPI_MOM', name: 'Core CPI M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Core Consumer Price Index (excl. food and energy) month-over-month change', ...US },
  { id: 'US.PRICES.CORE_CPI_YOY', name: 'Core CPI Y/Y', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Core Consumer Price Index (excl. food and energy) year-over-year change', ...US },
  { id: 'US.PRICES.PPI_MOM', name: 'PPI M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, externalIds: { slug: 'us-ppi' }, description: 'Producer Price Index month-over-month change', ...US },
  { id: 'US.PRICES.PPI_YOY', name: 'PPI Y/Y', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Producer Price Index year-over-year change', ...US },
  { id: 'US.PRICES.CORE_PPI_MOM', name: 'Core PPI M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Core Producer Price Index (excl. food and energy) month-over-month change', ...US },
  { id: 'US.PRICES.PCE_MOM', name: 'PCE Price Index M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Personal Consumption Expenditures Price Index month-over-month change', ...US },
  { id: 'US.PRICES.CORE_PCE_MOM', name: 'Core PCE Price Index M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Core Personal Consumption Expenditures Price Index month-over-month change', ...US },
  { id: 'US.PRICES.IMPORT_PRICE_MOM', name: 'Import Price Index M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Import Price Index month-over-month change', ...US },
  { id: 'US.PRICES.EXPORT_PRICE_MOM', name: 'Export Price Index M/M', type: EventType.Indicator, sector: EventSector.Prices, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Export Price Index month-over-month change', ...US },
] as const;

// ─── JOBS ─────────────────────────────────────────────────────────────
const JOBS_EVENTS: readonly EventDefinition[] = [
  { id: 'US.JOBS.NFP', name: 'Non-Farm Payrolls', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Job, multiplier: EventMultiplier.Thousands, digits: 0, externalIds: { slug: 'us-nfp' }, description: 'Change in the number of employed people excluding the farming sector', ...US },
  { id: 'US.JOBS.UNEMPLOYMENT_RATE', name: 'Unemployment Rate', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.High, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Percentage of the total workforce that is unemployed and actively seeking employment', ...US },
  { id: 'US.JOBS.AVG_HOURLY_EARNINGS_MOM', name: 'Average Hourly Earnings M/M', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Average hourly earnings month-over-month change', ...US },
  { id: 'US.JOBS.AVG_HOURLY_EARNINGS_YOY', name: 'Average Hourly Earnings Y/Y', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Average hourly earnings year-over-year change', ...US },
  { id: 'US.JOBS.JOLTS', name: 'JOLTS Job Openings', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Job, multiplier: EventMultiplier.Millions, digits: 2, externalIds: { slug: 'us-jolts' }, description: 'Job Openings and Labor Turnover Survey', ...US },
  { id: 'US.JOBS.ADP_EMPLOYMENT', name: 'ADP Employment Change', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Job, multiplier: EventMultiplier.Thousands, digits: 0, description: 'ADP private sector employment change', ...US },
  { id: 'US.JOBS.INITIAL_CLAIMS', name: 'Initial Jobless Claims', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Moderate, frequency: EventFrequency.Week, timeMode: EventTimeMode.DateTime, unit: EventUnit.Job, multiplier: EventMultiplier.Thousands, digits: 0, description: 'Number of initial unemployment insurance claims filed', ...US },
  { id: 'US.JOBS.CONTINUING_CLAIMS', name: 'Continuing Jobless Claims', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Low, frequency: EventFrequency.Week, timeMode: EventTimeMode.DateTime, unit: EventUnit.Job, multiplier: EventMultiplier.Thousands, digits: 0, description: 'Number of continuing unemployment insurance claims', ...US },
  { id: 'US.JOBS.LFPR', name: 'Labor Force Participation Rate', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Percentage of working-age population in the labor force', ...US },
  { id: 'US.JOBS.NONFARM_PRODUCTIVITY', name: 'Nonfarm Productivity Q/Q', type: EventType.Indicator, sector: EventSector.Jobs, importance: EventImportance.Low, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Nonfarm business sector labor productivity quarter-over-quarter change', ...US },
] as const;

// ─── GDP ──────────────────────────────────────────────────────────────
const GDP_EVENTS: readonly EventDefinition[] = [
  { id: 'US.GDP.GDP_QOQ', name: 'GDP Q/Q Annualized', type: EventType.Indicator, sector: EventSector.GDP, importance: EventImportance.Moderate, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, externalIds: { slug: 'us-gdp' }, description: 'Gross Domestic Product quarter-over-quarter annualized change', ...US },
  { id: 'US.GDP.GDP_PRICE_INDEX', name: 'GDP Price Index Q/Q', type: EventType.Indicator, sector: EventSector.GDP, importance: EventImportance.Low, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'GDP Price Index quarter-over-quarter change', ...US },
  { id: 'US.GDP.GDP_YOY', name: 'GDP Y/Y', type: EventType.Indicator, sector: EventSector.GDP, importance: EventImportance.Moderate, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Gross Domestic Product year-over-year change', ...US },
] as const;

// ─── CONSUMER ────────────────────────────────────────────────────────
const CONSUMER_EVENTS: readonly EventDefinition[] = [
  { id: 'US.CONSUMER.RETAIL_SALES_MOM', name: 'Retail Sales M/M', type: EventType.Indicator, sector: EventSector.Consumer, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, externalIds: { slug: 'us-retail' }, description: 'Total retail sales month-over-month change', ...US },
  { id: 'US.CONSUMER.CORE_RETAIL_SALES_MOM', name: 'Core Retail Sales M/M', type: EventType.Indicator, sector: EventSector.Consumer, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Core retail sales (excl. automobiles) month-over-month change', ...US },
  { id: 'US.CONSUMER.MICHIGAN_SENTIMENT', name: 'Michigan Consumer Sentiment', type: EventType.Indicator, sector: EventSector.Consumer, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'University of Michigan Consumer Sentiment Index', ...US },
  { id: 'US.CONSUMER.MICHIGAN_EXPECTATIONS', name: 'Michigan Consumer Expectations', type: EventType.Indicator, sector: EventSector.Consumer, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'University of Michigan Consumer Expectations Index', ...US },
  { id: 'US.CONSUMER.CB_CONFIDENCE', name: 'CB Consumer Confidence', type: EventType.Indicator, sector: EventSector.Consumer, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'Conference Board Consumer Confidence Index', ...US },
  { id: 'US.CONSUMER.PERSONAL_INCOME_MOM', name: 'Personal Income M/M', type: EventType.Indicator, sector: EventSector.Consumer, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Personal income month-over-month change', ...US },
  { id: 'US.CONSUMER.PERSONAL_SPENDING_MOM', name: 'Personal Spending M/M', type: EventType.Indicator, sector: EventSector.Consumer, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Personal spending month-over-month change', ...US },
] as const;

// ─── BUSINESS ────────────────────────────────────────────────────────
const BUSINESS_EVENTS: readonly EventDefinition[] = [
  { id: 'US.BUSINESS.MFG_PMI', name: 'ISM Manufacturing PMI', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, externalIds: { slug: 'us-pmi' }, description: 'Institute for Supply Management Manufacturing Purchasing Managers Index', ...US },
  { id: 'US.BUSINESS.NONMFG_PMI', name: 'ISM Non-Manufacturing PMI', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'Institute for Supply Management Non-Manufacturing (Services) PMI', ...US },
  { id: 'US.BUSINESS.ISM_MFG_PRICES', name: 'ISM Manufacturing Prices', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'ISM Manufacturing Prices Paid sub-index', ...US },
  { id: 'US.BUSINESS.ISM_MFG_EMPLOYMENT', name: 'ISM Manufacturing Employment', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'ISM Manufacturing Employment sub-index', ...US },
  { id: 'US.BUSINESS.SP_MFG_PMI', name: 'S&P Global Manufacturing PMI', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'S&P Global (Markit) Manufacturing Purchasing Managers Index', ...US },
  { id: 'US.BUSINESS.SP_SERVICES_PMI', name: 'S&P Global Services PMI', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'S&P Global (Markit) Services Purchasing Managers Index', ...US },
  { id: 'US.BUSINESS.SP_COMPOSITE_PMI', name: 'S&P Global Composite PMI', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 1, description: 'S&P Global (Markit) Composite Purchasing Managers Index', ...US },
  { id: 'US.BUSINESS.DURABLE_GOODS_MOM', name: 'Durable Goods Orders M/M', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Durable goods orders month-over-month change', ...US },
  { id: 'US.BUSINESS.FACTORY_ORDERS_MOM', name: 'Factory Orders M/M', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Factory orders month-over-month change', ...US },
  { id: 'US.BUSINESS.INDUSTRIAL_PRODUCTION_MOM', name: 'Industrial Production M/M', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Industrial production month-over-month change', ...US },
  { id: 'US.BUSINESS.CAPACITY_UTILIZATION', name: 'Capacity Utilization', type: EventType.Indicator, sector: EventSector.Business, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Percentage of industrial capacity in use', ...US },
] as const;

// ─── HOUSING ─────────────────────────────────────────────────────────
const HOUSING_EVENTS: readonly EventDefinition[] = [
  { id: 'US.HOUSING.EXISTING_HOME_SALES', name: 'Existing Home Sales', type: EventType.Indicator, sector: EventSector.Housing, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Building, multiplier: EventMultiplier.Millions, digits: 2, description: 'Annualized number of existing residential buildings sold', ...US },
  { id: 'US.HOUSING.NEW_HOME_SALES', name: 'New Home Sales', type: EventType.Indicator, sector: EventSector.Housing, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Building, multiplier: EventMultiplier.Thousands, digits: 0, description: 'Annualized number of new residential buildings sold', ...US },
  { id: 'US.HOUSING.BUILDING_PERMITS', name: 'Building Permits', type: EventType.Indicator, sector: EventSector.Housing, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Building, multiplier: EventMultiplier.Millions, digits: 2, description: 'Annualized number of new residential building permits issued', ...US },
  { id: 'US.HOUSING.HOUSING_STARTS', name: 'Housing Starts', type: EventType.Indicator, sector: EventSector.Housing, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Building, multiplier: EventMultiplier.Millions, digits: 2, description: 'Annualized number of new residential buildings on which construction has begun', ...US },
  { id: 'US.HOUSING.CASE_SHILLER_YOY', name: 'S&P/Case-Shiller Home Price Index Y/Y', type: EventType.Indicator, sector: EventSector.Housing, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'S&P/Case-Shiller Composite-20 Home Price Index year-over-year change', ...US },
  { id: 'US.HOUSING.PENDING_HOME_SALES_MOM', name: 'Pending Home Sales M/M', type: EventType.Indicator, sector: EventSector.Housing, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.Percent, multiplier: EventMultiplier.None, digits: 1, description: 'Pending home sales month-over-month change', ...US },
  { id: 'US.HOUSING.NAHB_INDEX', name: 'NAHB Housing Market Index', type: EventType.Indicator, sector: EventSector.Housing, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'National Association of Home Builders Housing Market Index', ...US },
] as const;

// ─── TRADE ───────────────────────────────────────────────────────────
const TRADE_EVENTS: readonly EventDefinition[] = [
  { id: 'US.TRADE.TRADE_BALANCE', name: 'Trade Balance', type: EventType.Indicator, sector: EventSector.Trade, importance: EventImportance.Moderate, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.USD, multiplier: EventMultiplier.Billions, digits: 1, description: 'Difference between exports and imports of goods and services', ...US },
  { id: 'US.TRADE.CURRENT_ACCOUNT', name: 'Current Account', type: EventType.Indicator, sector: EventSector.Trade, importance: EventImportance.Low, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.DateTime, unit: EventUnit.USD, multiplier: EventMultiplier.Billions, digits: 1, description: 'Current account balance (trade, income, and transfers)', ...US },
] as const;

// ─── GOVERNMENT ──────────────────────────────────────────────────────
const GOVERNMENT_EVENTS: readonly EventDefinition[] = [
  { id: 'US.GOVERNMENT.FEDERAL_BUDGET', name: 'Federal Budget Balance', type: EventType.Indicator, sector: EventSector.Government, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.USD, multiplier: EventMultiplier.Billions, digits: 1, description: 'Federal government budget surplus or deficit', ...US },
  { id: 'US.GOVERNMENT.TIC', name: 'Treasury International Capital (TIC)', type: EventType.Indicator, sector: EventSector.Government, importance: EventImportance.Low, frequency: EventFrequency.Month, timeMode: EventTimeMode.DateTime, unit: EventUnit.USD, multiplier: EventMultiplier.Billions, digits: 1, description: 'Net foreign purchases of US Treasury securities', ...US },
  { id: 'US.GOVERNMENT.BUDGET_RELEASE', name: 'US Federal Budget Release', type: EventType.Event, sector: EventSector.Government, importance: EventImportance.Moderate, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'US federal budget proposal release', ...US },
  { id: 'US.GOVERNMENT.TAX_REFORM', name: 'US Tax Reform Event', type: EventType.Event, sector: EventSector.Government, importance: EventImportance.High, frequency: EventFrequency.None, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Major US tax reform legislation signing or vote', ...US },
  { id: 'US.GOVERNMENT.INFRASTRUCTURE_BILL', name: 'US Infrastructure Bill', type: EventType.Event, sector: EventSector.Government, importance: EventImportance.Moderate, frequency: EventFrequency.None, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Major US infrastructure spending bill passage', ...US },
] as const;

// ─── HOLIDAYS ────────────────────────────────────────────────────────
const HOLIDAYS_EVENTS: readonly EventDefinition[] = [
  { id: 'US.HOLIDAYS.MLK_DAY', name: 'Martin Luther King Jr. Day', type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.Low, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'MLK Day — US markets closed', ...US },
  { id: 'US.HOLIDAYS.PRESIDENTS_DAY', name: "Presidents' Day", type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.Low, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: "Presidents' Day — US markets closed", ...US },
  { id: 'US.HOLIDAYS.MEMORIAL_DAY', name: 'Memorial Day', type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.Low, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Memorial Day — US markets closed', ...US },
  { id: 'US.HOLIDAYS.INDEPENDENCE_DAY', name: 'Independence Day', type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.Low, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Independence Day — US markets closed', ...US },
  { id: 'US.HOLIDAYS.LABOR_DAY', name: 'Labor Day', type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.Low, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Labor Day — US markets closed', ...US },
  { id: 'US.HOLIDAYS.COLUMBUS_DAY', name: 'Columbus Day', type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.None, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Columbus Day — US bond markets closed', ...US },
  { id: 'US.HOLIDAYS.VETERANS_DAY', name: 'Veterans Day', type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.None, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Veterans Day — US bond markets closed', ...US },
  { id: 'US.HOLIDAYS.THANKSGIVING', name: 'Thanksgiving', type: EventType.Holiday, sector: EventSector.Holidays, importance: EventImportance.Low, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Thanksgiving — US markets closed', ...US },
] as const;

// ─── MISC ─────────────────────────────────────────────────────────────
const MISC_EVENTS: readonly EventDefinition[] = [
  { id: 'US.FUTURES.TRIPLE_WITCHING', name: 'Triple Witching', type: EventType.Event, sector: EventSector.Futures, importance: EventImportance.Moderate, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'Simultaneous expiry of stock options, index options, and index futures', ...US },
  { id: 'WW.MARKET.SUPER_BOWL', name: 'Super Bowl', type: EventType.Event, sector: EventSector.Market, importance: EventImportance.Low, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'NFL Super Bowl (Super Bowl indicator)', ...US },
  { id: 'US.MARKET.GOVERNMENT_SHUTDOWN', name: 'US Government Shutdown', type: EventType.Event, sector: EventSector.Market, importance: EventImportance.Moderate, frequency: EventFrequency.None, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'US federal government shutdown', ...US },
  { id: 'US.MARKET.DEBT_CEILING', name: 'US Debt Ceiling Crisis', type: EventType.Event, sector: EventSector.Market, importance: EventImportance.High, frequency: EventFrequency.None, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'US federal debt ceiling deadline', ...US },
  { id: 'US.MARKET.CONGRESSIONAL_TRADING', name: 'Congressional Trading Disclosure', type: EventType.Event, sector: EventSector.Market, importance: EventImportance.Low, frequency: EventFrequency.None, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'US congressional stock trading disclosure filing', ...US },
  { id: 'US.CALENDAR.TAX_DEADLINE', name: 'US Tax Filing Deadline', type: EventType.Event, sector: EventSector.Calendar, importance: EventImportance.Moderate, frequency: EventFrequency.Year, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'US federal income tax filing deadline (April 15)', ...US },
  { id: 'US.CALENDAR.ESTIMATED_TAX', name: 'US Estimated Tax Payment', type: EventType.Event, sector: EventSector.Calendar, importance: EventImportance.Low, frequency: EventFrequency.Quarter, timeMode: EventTimeMode.Date, unit: EventUnit.None, multiplier: EventMultiplier.None, digits: 0, description: 'US quarterly estimated tax payment deadline', ...US },
] as const;

export const US_EVENTS: readonly EventDefinition[] = [
  ...MONEY_EVENTS,
  ...PRICES_EVENTS,
  ...JOBS_EVENTS,
  ...GDP_EVENTS,
  ...CONSUMER_EVENTS,
  ...BUSINESS_EVENTS,
  ...HOUSING_EVENTS,
  ...TRADE_EVENTS,
  ...GOVERNMENT_EVENTS,
  ...HOLIDAYS_EVENTS,
  ...MISC_EVENTS,
] as const;
